version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.17.0
    command: /usr/local/bin/envoy -c /etc/envoy.yaml --service-cluster envoy-proxy
    ports:
    - "10000:10000"
    - "9901:9901"
    volumes:
    - ./envoy.yaml:/etc/envoy.yaml
  sink:
    build:
      context: ../
      dockerfile: Dockerfile
    command: /usr/local/bin/sink
    expose:
    - "9001"
