version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:latest
    command: /usr/local/bin/envoy -c /etc/envoy.yaml --service-cluster envoy-proxy
    ports:
    - "10000:10000"
    - "9901:9901"
    volumes:
    - ./envoy.yaml:/etc/envoy.yaml
  sink:
    image: gcr.io/tetrate-internal-containers/metrics-sink-debugger:0.0.1
    command: /usr/local/bin/sink
    expose:
    - "9001"
